### PR TITLE
support for multiple status code entries

### PR DESCRIPTION
**Pull request by YaroslavYaroslavtsev**
https://github.com/google/oatts/issues/8 support for multiple status code entries in custom values

### CODE REVIEW

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I fixed it.

**Comment by noahdietz** [comment]
Hi there, thanks for the feature. You've opened the PR via @YaroslavYaroslavtsev but you made the commit via @YrslvSdevel. That is why the CLA bot is confused. Please resolve this.

**Comment by YrslvSdevel** [comment]
I fixed it.

**Comment by YrslvSdevel** [comment]
@googlebot I fixed it.

**Comment by YrslvSdevel** [comment]
@googlebot I signed it!

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I fixed it.

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I signed it!

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I fixed it

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I signed it!

**Comment by raoulus** [comment]
Hi @noahdietz, I think this is not part of the latest release (1.6.0). Is it possible to have a new release including this PR?

**Pull request merged**
