### PR TITLE
support for multiple status code entries

### PR DESCRIPTION
**Pull request by YaroslavYaroslavtsev**
https://github.com/google/oatts/issues/8

### CODE REVIEW

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I signed it!

**Comment by YaroslavYaroslavtsev** [comment]
@googlebot I fixed it.

**Comment by raoulus** [comment]
hi @YaroslavYaroslavtsev, I don't see this PR being part of the latest release 1.6.0. Any chance to release a new version including this? Thanks!

**Comment by YaroslavYaroslavtsev** [comment]
See PR #36

**Pull request closed without merging**
